// SPDX-License-Identifier: Apache-2.0
#pragma once

#include "cdfmm/geometry/models.hpp"
#include "cdfmm/geometry/primitives/rectangular_prism.hpp"
#include "cdfmm/geometry/primitives/tetrahedron.hpp"
#include "cdfmm/cuboid.hpp"
#include "cdfmm/cuda_cuboid.hpp"

// Convenience umbrella header for the complete public C++ interface.
#include "cdfmm/core/output_flags.hpp"
#include "cdfmm/core/precision.hpp"
#include "cdfmm/math/coefficients.hpp"
#include "cdfmm/math/laplace_derivatives.hpp"
#include "cdfmm/math/multi_index.hpp"
#include "cdfmm/math/pair_tensor.hpp"
#include "cdfmm/math/potential_field.hpp"
#include "cdfmm/math/spherical_harmonics.hpp"
#include "cdfmm/math/taylor_jet.hpp"
#include "cdfmm/math/vec3.hpp"
#include "cdfmm/operators.hpp"
#include "cdfmm/periodic.hpp"
#include "cdfmm/parameter_selection.hpp"
#include "cdfmm/static_operators.hpp"
#include "cdfmm/static_topology.hpp"
#include "cdfmm/tree/adaptive_tree.hpp"
#include "cdfmm/tree/indexing.hpp"
#include "cdfmm/tree/morton.hpp"
#include "cdfmm/tree/node.hpp"
#include "cdfmm/tree/statistics.hpp"
#include "cdfmm/tree/uniform_tree.hpp"
#include "cdfmm/uniform_fmm.hpp"
#include "cdfmm/validation.hpp"
